name: Update anime-lists
on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * SUN
jobs:
  update-list:
    #only update in the main repository
    if: ${{ github.repository_owner == 'Anime-Lists' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install libxml2
        run: sudo apt-get install xsltproc
      - name: Update
        run: |
          ./update.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update to latest animetitles.xml
          commit_author: Github Actions <actions@github.com>
