name: Validate XML
on:
  pull_request:
    branches: ['master']
  workflow_dispatch:
jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Validate XML
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          for f in *.xml; do xmllint --noout --valid "$f"; done
