name: Validate XML
on:
  pull_request:
    branches: ['master']
    paths:
      - anime-list-master.xml
      - anime-movieset-list.xml
  workflow_dispatch:
jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate XML
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          for f in *.xml; do xmllint --noout --valid "$f"; done
